name: Scene
options:
  deploymentTarget:
    macOS: "14.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
targets:
  SceneApp:
    type: application
    platform: macOS
    deploymentTarget: "14.0"
    sources:
      - path: Sources/SceneApp
      - path: Resources
        optional: true
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_NAME: SceneApp
        PRODUCT_BUNDLE_IDENTIFIER: com.karpov.SceneApp
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
schemes:
  SceneApp:
    build:
      targets:
        SceneApp: all
    run:
      config: Debug
    archive:
      config: Release
